/*
 * This file is generated by jOOQ.
 */
package com.reunium.blog.jooq;


import com.reunium.blog.jooq.tables.EventRegistration;


/**
 * Convenience access to all tables in form-stack
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>form-stack.event-registration</code>.
     */
    public static final EventRegistration EVENT_REGISTRATION = EventRegistration.EVENT_REGISTRATION;
}
