/*
 * This file is generated by jOOQ.
 */
package com.reunium.blog.jooq.tables.records;


import com.reunium.blog.jooq.tables.EventRegistration;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventRegistrationRecord extends UpdatableRecordImpl<EventRegistrationRecord> implements Record16<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> {

    private static final long serialVersionUID = -33981243;

    /**
     * Setter for <code>form-stack.event-registration.uniqueID</code>.
     */
    public void setUniqueid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.uniqueID</code>.
     */
    public String getUniqueid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>form-stack.event-registration.formID</code>.
     */
    public void setFormid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.formID</code>.
     */
    public String getFormid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>form-stack.event-registration.personal_information</code>.
     */
    public void setPersonalInformation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.personal_information</code>.
     */
    public String getPersonalInformation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>form-stack.event-registration.name_first</code>.
     */
    public void setNameFirst(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.name_first</code>.
     */
    public String getNameFirst() {
        return (String) get(3);
    }

    /**
     * Setter for <code>form-stack.event-registration.name_last</code>.
     */
    public void setNameLast(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.name_last</code>.
     */
    public String getNameLast() {
        return (String) get(4);
    }

    /**
     * Setter for <code>form-stack.event-registration.address_address</code>.
     */
    public void setAddressAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.address_address</code>.
     */
    public String getAddressAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>form-stack.event-registration.address_city</code>.
     */
    public void setAddressCity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.address_city</code>.
     */
    public String getAddressCity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>form-stack.event-registration.address_state</code>.
     */
    public void setAddressState(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.address_state</code>.
     */
    public String getAddressState() {
        return (String) get(7);
    }

    /**
     * Setter for <code>form-stack.event-registration.address_zip</code>.
     */
    public void setAddressZip(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.address_zip</code>.
     */
    public String getAddressZip() {
        return (String) get(8);
    }

    /**
     * Setter for <code>form-stack.event-registration.address_country</code>.
     */
    public void setAddressCountry(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.address_country</code>.
     */
    public String getAddressCountry() {
        return (String) get(9);
    }

    /**
     * Setter for <code>form-stack.event-registration.email</code>.
     */
    public void setEmail(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.email</code>.
     */
    public String getEmail() {
        return (String) get(10);
    }

    /**
     * Setter for <code>form-stack.event-registration.event_information</code>.
     */
    public void setEventInformation(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.event_information</code>.
     */
    public String getEventInformation() {
        return (String) get(11);
    }

    /**
     * Setter for <code>form-stack.event-registration.will_you_be_attending</code>.
     */
    public void setWillYouBeAttending(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.will_you_be_attending</code>.
     */
    public String getWillYouBeAttending() {
        return (String) get(12);
    }

    /**
     * Setter for <code>form-stack.event-registration.number_attending</code>.
     */
    public void setNumberAttending(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.number_attending</code>.
     */
    public String getNumberAttending() {
        return (String) get(13);
    }

    /**
     * Setter for <code>form-stack.event-registration.amount</code>.
     */
    public void setAmount(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.amount</code>.
     */
    public String getAmount() {
        return (String) get(14);
    }

    /**
     * Setter for <code>form-stack.event-registration.upload</code>.
     */
    public void setUpload(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>form-stack.event-registration.upload</code>.
     */
    public String getUpload() {
        return (String) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row16<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    @Override
    public Row16<String, String, String, String, String, String, String, String, String, String, String, String, String, String, String, String> valuesRow() {
        return (Row16) super.valuesRow();
    }

    @Override
    public Field<String> field1() {
        return EventRegistration.EVENT_REGISTRATION.UNIQUEID;
    }

    @Override
    public Field<String> field2() {
        return EventRegistration.EVENT_REGISTRATION.FORMID;
    }

    @Override
    public Field<String> field3() {
        return EventRegistration.EVENT_REGISTRATION.PERSONAL_INFORMATION;
    }

    @Override
    public Field<String> field4() {
        return EventRegistration.EVENT_REGISTRATION.NAME_FIRST;
    }

    @Override
    public Field<String> field5() {
        return EventRegistration.EVENT_REGISTRATION.NAME_LAST;
    }

    @Override
    public Field<String> field6() {
        return EventRegistration.EVENT_REGISTRATION.ADDRESS_ADDRESS;
    }

    @Override
    public Field<String> field7() {
        return EventRegistration.EVENT_REGISTRATION.ADDRESS_CITY;
    }

    @Override
    public Field<String> field8() {
        return EventRegistration.EVENT_REGISTRATION.ADDRESS_STATE;
    }

    @Override
    public Field<String> field9() {
        return EventRegistration.EVENT_REGISTRATION.ADDRESS_ZIP;
    }

    @Override
    public Field<String> field10() {
        return EventRegistration.EVENT_REGISTRATION.ADDRESS_COUNTRY;
    }

    @Override
    public Field<String> field11() {
        return EventRegistration.EVENT_REGISTRATION.EMAIL;
    }

    @Override
    public Field<String> field12() {
        return EventRegistration.EVENT_REGISTRATION.EVENT_INFORMATION;
    }

    @Override
    public Field<String> field13() {
        return EventRegistration.EVENT_REGISTRATION.WILL_YOU_BE_ATTENDING;
    }

    @Override
    public Field<String> field14() {
        return EventRegistration.EVENT_REGISTRATION.NUMBER_ATTENDING;
    }

    @Override
    public Field<String> field15() {
        return EventRegistration.EVENT_REGISTRATION.AMOUNT;
    }

    @Override
    public Field<String> field16() {
        return EventRegistration.EVENT_REGISTRATION.UPLOAD;
    }

    @Override
    public String component1() {
        return getUniqueid();
    }

    @Override
    public String component2() {
        return getFormid();
    }

    @Override
    public String component3() {
        return getPersonalInformation();
    }

    @Override
    public String component4() {
        return getNameFirst();
    }

    @Override
    public String component5() {
        return getNameLast();
    }

    @Override
    public String component6() {
        return getAddressAddress();
    }

    @Override
    public String component7() {
        return getAddressCity();
    }

    @Override
    public String component8() {
        return getAddressState();
    }

    @Override
    public String component9() {
        return getAddressZip();
    }

    @Override
    public String component10() {
        return getAddressCountry();
    }

    @Override
    public String component11() {
        return getEmail();
    }

    @Override
    public String component12() {
        return getEventInformation();
    }

    @Override
    public String component13() {
        return getWillYouBeAttending();
    }

    @Override
    public String component14() {
        return getNumberAttending();
    }

    @Override
    public String component15() {
        return getAmount();
    }

    @Override
    public String component16() {
        return getUpload();
    }

    @Override
    public String value1() {
        return getUniqueid();
    }

    @Override
    public String value2() {
        return getFormid();
    }

    @Override
    public String value3() {
        return getPersonalInformation();
    }

    @Override
    public String value4() {
        return getNameFirst();
    }

    @Override
    public String value5() {
        return getNameLast();
    }

    @Override
    public String value6() {
        return getAddressAddress();
    }

    @Override
    public String value7() {
        return getAddressCity();
    }

    @Override
    public String value8() {
        return getAddressState();
    }

    @Override
    public String value9() {
        return getAddressZip();
    }

    @Override
    public String value10() {
        return getAddressCountry();
    }

    @Override
    public String value11() {
        return getEmail();
    }

    @Override
    public String value12() {
        return getEventInformation();
    }

    @Override
    public String value13() {
        return getWillYouBeAttending();
    }

    @Override
    public String value14() {
        return getNumberAttending();
    }

    @Override
    public String value15() {
        return getAmount();
    }

    @Override
    public String value16() {
        return getUpload();
    }

    @Override
    public EventRegistrationRecord value1(String value) {
        setUniqueid(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value2(String value) {
        setFormid(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value3(String value) {
        setPersonalInformation(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value4(String value) {
        setNameFirst(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value5(String value) {
        setNameLast(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value6(String value) {
        setAddressAddress(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value7(String value) {
        setAddressCity(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value8(String value) {
        setAddressState(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value9(String value) {
        setAddressZip(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value10(String value) {
        setAddressCountry(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value11(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value12(String value) {
        setEventInformation(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value13(String value) {
        setWillYouBeAttending(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value14(String value) {
        setNumberAttending(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value15(String value) {
        setAmount(value);
        return this;
    }

    @Override
    public EventRegistrationRecord value16(String value) {
        setUpload(value);
        return this;
    }

    @Override
    public EventRegistrationRecord values(String value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventRegistrationRecord
     */
    public EventRegistrationRecord() {
        super(EventRegistration.EVENT_REGISTRATION);
    }

    /**
     * Create a detached, initialised EventRegistrationRecord
     */
    public EventRegistrationRecord(String uniqueid, String formid, String personalInformation, String nameFirst, String nameLast, String addressAddress, String addressCity, String addressState, String addressZip, String addressCountry, String email, String eventInformation, String willYouBeAttending, String numberAttending, String amount, String upload) {
        super(EventRegistration.EVENT_REGISTRATION);

        set(0, uniqueid);
        set(1, formid);
        set(2, personalInformation);
        set(3, nameFirst);
        set(4, nameLast);
        set(5, addressAddress);
        set(6, addressCity);
        set(7, addressState);
        set(8, addressZip);
        set(9, addressCountry);
        set(10, email);
        set(11, eventInformation);
        set(12, willYouBeAttending);
        set(13, numberAttending);
        set(14, amount);
        set(15, upload);
    }
}
